baseURL = "https://www.derguene.sn"
disableLanguages = []
paginate = "4"
summaryLength = "10"
theme = "gofolium"
title = "Derguene | Personal Website"
[Languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"
languageCode = "fr-fr"
languageName = "Fr"
weight = 2
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
URL = "home"
name = "home"
weight = 1
[[menu.main]]
URL = "about"
name = "about"
weight = 2
[[menu.main]]
URL = "publication"
name = "publication"
weight = 3
[[menu.main]]
URL = "talk"
name = "talk"
weight = 4
[[menu.main]]
URL = "project"
name = "project"
weight = 5
[[menu.main]]
URL = "blog"
name = "blog"
weight = 6
[[menu.main]]
URL = "contact"
name = "contact"
weight = 7
[params]
author = "Themefisher"
description = "Welcome to my Meta World!"
google_analitycs_id = ""
logo = "images/logo.png"
particles = true
[params.navigation_button]
enable = true
label = "contact"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/particles/particles.min.js"
[[params.plugins.js]]
link = "plugins/particles/stats.min.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
icon = "ti-google"
link = "https://scholar.google.com/citations?user=ULCkfdQAAAAJ"
title = "google"
[[params.social]]
icon = "ti-linkedin"
link = "https://www.linkedin.com/in/derguene-mbaye/"
title = "linkedin"
[[params.social]]
icon = "ti-github"
link = "https://github.com/DerXter/"
title = "github"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/derguene"
title = "twitter"
